### PR TITLE
resizable buttons

### PR DESCRIPTION
**Pull request by 1C0D**
You can set the size of the buttons in settings and get them back to default value.  
The only thing I didn't touch was in /* @settings ... */ in the CSS sheet, because I'm not sure about what to do there. I think I know for what it is, a plugin to set CSS prefs, but not 100% sure.

### CODE REVIEW

**Comment by cloudhao1999** [comment]
> You can set the size of the buttons in settings and get them back to default value. The only thing I didn't touch was in /* @settings ... */ in the CSS sheet, because I'm not sure about what to do there. I think I know for what it is, a plugin to set CSS prefs, but not 100% sure.

Thank you for your contribution, but I don't quite understand the purpose of this new addition. Is it intended for users who haven't installed Style Settings plugin? Because the existing CSS settings can also be manually modified to achieve changes in position.

**Comment by cloudhao1999** [comment]
> You can set the size of the buttons in settings and get them back to default value. The only thing I didn't touch was in /* @settings ... */ in the CSS sheet, because I'm not sure about what to do there. I think I know for what it is, a plugin to set CSS prefs, but not 100% sure.

Because the em unit itself is a relative unit, it may change with the system font size setting. Personally, I feel that using this scaling parameter may cause some confusion.

**Comment by cloudhao1999** [comment]
After thinking about it, I realized that this setting can quickly modify the global style and may be convenient for some users to customize the position of buttons. It's a good idea, but I'm currently busy with work, so I can only merge your code for now. Thank you for your support.

**Comment by 1C0D** [comment]
I don't have this plugin, indeed, on the thousand existing. This is a setting to change the size of the buttons, in function of your use. I even thought about a size option linked to window size. The scale is for applying a scaling around 1 to all settings at once. Size, space between, right, bottom. If not, the button can be too far from the right side, going smaller, or superposed, going bigger.  I think this is a useful feature for most people not familiar with CSS or plugins around it. But I will take a look at this plugin later. Did you notice the documentElement to call the variable from the :root ? go to know...

**Comment by cloudhao1999** [comment]
> I don't have this plugin, indeed, on the thousand existing. This is a setting to change the size of the buttons, in function of your use. I even thought about a size option linked to window size. The scale is for applying a scaling around 1 to all settings at once. Size, space between, right, bottom. If not, the button can be too far from the right side, going smaller, or superposed, going bigger. I think this is a useful feature for most people not familiar with CSS or plugins around it. But I will take a look at this plugin later. Did you notice the documentElement to call the variable from the :root ? good to know...

Yes, this new feature can make it easier for users who are not familiar with CSS to adjust styles, but I still need to make some adjustments to be compatible with the style settings plugin

**Pull request merged**
