### PR TITLE
ctrl open file fixed & optimizations

### PR DESCRIPTION
**Pull request by 1C0D**
I fixed the bug when opening a file with ctrl and buttons were disappearing. The visible file was no more active.
So it's still testing if the opened tab is a markdown, but not necessary active. Maybe hard to understand, but it's working well now.
I simplified and optimized scroll to bottom.
A register was added to each workspace.on which is important for a clean unregistering.
the open-file was redundant if already using on layout-change which include opening a file...

### CODE REVIEW

**Comment by 1C0D** [comment]
I forgot to mention the bug was happening if the preference "always focus new tabs" was turned off.

**Comment by cloudhao1999** [comment]
Thank you very much for your support of this plugin. However, I have been quite busy with work recently, so I may need to review this PR over the weekend. Thank you for your submission.

**Comment by 1C0D** [comment]
cool 👍 I can add you a gif to help to see the bug
gifbug

**Comment by 1C0D** [comment]
I'm so sorry that you were so exhausted by me :rofl: I didn't make it on purpose...

**Comment by cloudhao1999** [comment]
> I'm so sorry that you were so exhausted by me 🤣 I didn't make it on purpose...

Is there any problem that caused the closure of this pull request? Due to work reasons, I didn't have time to review this submission during this period. If I have time, I will merge this request. Sorry about that.

**Comment by cloudhao1999** [comment]
I will maintain the original monitoring, and your modifications to the scrolling method will be preserved. Thank you very much for your support of this project.

**Comment by cloudhao1999** [comment]
The expected result

**Comment by cloudhao1999** [comment]
> The expected result

iShot_2023-07-29_09 38 28

**Comment by cloudhao1999** [comment]
The latest version 2.1.1 already includes this change.

**Comment by 1C0D** [comment]
hmm, I answered but didn't mean to close it. But  you saw some parts of what I did, that was the purpose. I discovered very recently, on my one of my plugins "close similar tabs" that the intended update of closing tabs was due to another activated plugin I did "reveal file in explorer". So I remember it was not obvious to me that the on open-file was needed over on active-leaf-change, even with your plugin. It was working well without it, because of this plugin updating the state of new opened files. Really strange. I get to fix that quickly.

**Pull request merged**
