### PR TITLE
show/hide buttons without clicking on the document

### PR DESCRIPTION
**Pull request by 1C0D**
Updates about showing hiding buttons are now made when opening files,   
so clicking on the document is no more needed.
It works in every window (using activeDocument) and only on markdown files
  
N.B: I did mistakes in my previous pullrequest (that I closed): 
- not using this.app.workspace.getActiveViewOfType(MarkdownView) but activeLeaf.view, it was working on image too 🤣 
- detecting empty tabs was not needed. activeView is doing it...
- I replaced document by activeDocument, to make it work in every window.
To make some tests, I restarted without any document in the main window and some in another window. That's ok

### CODE REVIEW

**Comment by cloudhao1999** [comment]
> Updates about showing hiding buttons are now made when opening files, so clicking on the document is no more needed. It works in every window (using activeDocument) and only on markdown files
> 
> N.B: I did mistakes in my previous pullrequest (that I closed):
> 
> * not using this.app.workspace.getActiveViewOfType(MarkdownView) but activeLeaf.view, it was working on image too 🤣
> * detecting empty tabs was not needed. activeView is doing it...
> * I replaced document by activeDocument, to make it work in every window.
>   To make some tests, I restarted without any document in the main window and some in another window. That's ok

Thank you for your attention to this plugin! I have learned that the `activeLeaf.view` property has been deprecated and may no longer be available in future versions. Thank you for being meticulous. Due to busy work, this plugin has not been updated for a long time. I also appreciate your contribution to making this plugin suitable for more interfaces.

**Comment by 1C0D** [comment]
No problem, I'm not hurry. I'm doing right now another modification. I added a button to go to selection or cursor. And that's working. But I need to understand a little more the process, to see all possibilities. 
And doing this I noticed the cursor position was lost, when scrolling in general, so I will add a save-restore of the cursor too... 
But your code is pure gold at base. I can't do something so well organized, for the moment. And among a lot of code I saw, this is really super clear.

**Comment by 1C0D** [comment]
I did more things working, but first I need to fix a major issue about dealing with new windows, because I've just ignored some of your code around new windows. I saw this later doing more modifications. 
What I did is to add a button to toggle (centered) to selection. so If you lost your selection or cursor position, you can quickly find it back. In this case of course, selection is preserved.
I modified a scroll to bottom same in source mode that in edit mode with some space at the end.
If scrolling down or up the cursor is going at the end or start (in source mode of course)
So I need time to see these things around multiwindows at first. 
And if I push other modifications I did, it will just be a mess by your side. 
It's hard to handle github for me. I need to see lessons about this later.

**Comment by 1C0D** [comment]
I was fed up with searching why I had a bug reloading with an opened window, so I deleted all optional things, and that's perfectly working. So I guess I need to rebuild all what I deleted step by step.
```
import {
	MarkdownView,
	Plugin,
	ButtonComponent,
	WorkspaceParent,
	WorkspaceWindow,
} from "obsidian";
import { ScrollToTopSettingType, scrollToTopSetting } from "./src/setting";
import { isContainSurfingWebview } from "plugins/surfing";

const ROOT_WORKSPACE_CLASS = ".mod-vertical.mod-root";

export default class ScrollToTopPlugin extends Plugin {
	settings: ScrollToTopSettingType;
	windowSet: Set<Window> = new Set();

	private createScrollElement(
		config: {
			id: string;
			className: string;
			icon: string;
			curWindow?: Window;
			tooltipConfig: {
				showTooltip: boolean;
				tooltipText: string;
			};
		},
		fn: () => void
	) {
		let topWidget = createEl("div");
		topWidget.setAttribute("class", `div-${config.className}`);
		topWidget.setAttribute("id", config.id);

		let button = new ButtonComponent(topWidget);
		button.setIcon(config.icon).setClass("buttonItem").onClick(fn);

		if (config.tooltipConfig.showTooltip) {
			button.setTooltip(config.tooltipConfig.tooltipText);
		}

		let curWindow = config.curWindow || window;

		curWindow.document.body
			.querySelector(ROOT_WORKSPACE_CLASS)
			?.insertAdjacentElement("afterbegin", topWidget);

		const activeLeaf = app.workspace.getActiveViewOfType(MarkdownView);

		if (!isContainSurfingWebview(this.settings) || !activeLeaf) {
			topWidget.style.visibility = "hidden";
		}
	}

	public removeButton(id: string, curWindow?: Window) {
		let curWin = curWindow || window;
		const element = curWin.activeDocument.getElementById(id);
		if (element) {
			element.remove();
		}
	}

	public createButton(window?: Window) {
		const {
			enabledScrollToTop,
			enabledScrollToBottom,
			iconScrollToTop,
			iconScrollToBottom,
			showTooltip,
			scrollTopTooltipText,
			scrollBottomTooltipText,
		} = this.settings;

		if (enabledScrollToTop) {
			// create a button
			this.createScrollElement(
				{
					id: "__C_scrollToTop",
					className: "scrollToTop",
					icon: iconScrollToTop,
					curWindow: window,
					tooltipConfig: {
						showTooltip,
						tooltipText: scrollTopTooltipText,
					},
				},
				() => {
					console.log("toTop");
				}
			);
		}

		if (enabledScrollToBottom) {
			this.createScrollElement(
				{
					id: "__C_scrollToBottom",
					className: "scrollToBottom",
					icon: iconScrollToBottom,
					curWindow: window,
					tooltipConfig: {
						showTooltip,
						tooltipText: scrollBottomTooltipText,
					},
				},
				() => {
					console.log("toBottom");
				}
			);
		}
	}

	async onload() {
		await this.loadSettings();

		this.app.workspace.onLayoutReady(() => {
			this.createButton();

			// when opening new file
			this.registerEvent(
				this.app.workspace.on("file-open", () => {
					const activeLeaf =
						app.workspace.getActiveViewOfType(MarkdownView);
					let BottomButton = activeDocument.querySelector(
						//activeDocument indispensable
						".div-scrollToBottom"
					) as HTMLElement;
					let TopButton = activeDocument.querySelector(
						".div-scrollToTop"
					) as HTMLElement;
					if (
						!activeLeaf
						// && //indispensable
						// !isContainSurfingWebview(this.settings)
					) {
						if (BottomButton)
							BottomButton.style.visibility = "hidden";
						if (TopButton) TopButton.style.visibility = "hidden";
					} else {
						if (BottomButton)
							BottomButton.style.visibility = "visible";
						if (TopButton) TopButton.style.visibility = "visible";
					}
				})
			);
		});

		// add popup window support
		this.app.workspace.on("window-open", (win, window) => {
			console.log("windowSet", this.windowSet);
			this.windowSet.add(window);
			this.createButton(window);
			let BottomButton = window.document.querySelector(
				//activeDocument indispensable
				".div-scrollToBottom"
			) as HTMLElement;
			let TopButton = window.document.querySelector(
				".div-scrollToTop"
			) as HTMLElement;
			if (BottomButton) BottomButton.style.visibility = "visible";
			if (TopButton) TopButton.style.visibility = "visible";
		});
		this.app.workspace.on("window-close", (win, window) => {
			this.windowSet.delete(window);
		});

		setTimeout(() => {
			this.app.workspace.trigger("css-change");
		}, 300);
	}
	async loadSettings() {
		this.settings = Object.assign(
			{},
			scrollToTopSetting,
			await this.loadData()
		);
	}

	onunload() {
		this.removeButton("__C_scrollToTop");
		this.removeButton("__C_scrollToBottom");
		// for popup window
		if (this.windowSet.size > 0) {
			this.windowSet.forEach((window) => {
				this.removeButton("__C_scrollToTop", window);
				this.removeButton("__C_scrollToBottom", window);
			});
		}
	}
	getRootSplits() {
		const rootSplits = [];
		// push the main window's root split to the list
		rootSplits.push(this.app.workspace.rootSplit);
		const floatingSplit = (this.app.workspace as any).floatingSplit;
		if (floatingSplit) {
			floatingSplit.children.forEach((child: WorkspaceParent) => {
				// if this is a window, push it to the list
				if (child instanceof WorkspaceWindow) {
					rootSplits.push(child);
				}
			});
		}
		return rootSplits;
	}
}
```

**Pull request merged**
